version: '3.8'

services:
    stratum:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:${SERVER_PORT:-8080}"
        env_file: .env
        environment:
            - REDIS_URL=redis:6379
            - SERVER_PORT=${SERVER_PORT:-8080}
        depends_on:
            - redis

    redis:
        image: "redis:8-alpine"
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data

volumes:
    redis_data:
